name: HyperCPU CI/CD Pipeline (update Docker images)

on:
  push:

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    name: "Update ${{ matrix.config.name }} Docker image"
    strategy:
      matrix:
        config:
          - tag: fedora
            name: Fedora
          - tag: debian-stable
            name: Debian Stable
          - tag: debian-unstable
            name: Debian Unstable
          - tag: archlinux
            name: Arch Linux
          - tag: gentoo-glibc
            name: Gentoo GLibc
          - tag: gentoo-musl
            name: Gentoo Musl
          - tag: alpine
            name: Alpine
          - tag: ubuntu
            name: Ubuntu
    
    steps:
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: hyperwin
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{ defaultContext }}:docker/${{ matrix.config.tag }}"
          push: true
          tags: hyperwin/hcpu-ci:${{ matrix.config.tag }}

