name: HyperCPU CI/CD Pipeline (feature branch)

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    container: hyperwin/hcpu-ci:debian-unstable
    if: (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev') || !contains(github.event.head_commit.message, '[ci skip]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Build and test with GCC on Release profile
        run: |
          cmake -S. -Bbuild -DHCPU_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target build-all-tests-github -j4
          build/modular_testing --gtest_brief
          build/integration_testing --gtest_brief
          rm -rf build
      
      - name: Build and test with LLVM on Release profile
        run: |
          cmake -S. -Bbuild -DHCPU_COMPILER=clang -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target build-all-tests-github -j4
          build/modular_testing --gtest_brief
          build/integration_testing --gtest_brief
          
      - name: Lint code
        run: |
          cp build/compile_commands.json .
          cppcheck --project=compile_commands.json --check-level=exhaustive -idist -j4
      
      - name: Clean up
        run: |
          rm -rf build
